"""initial schema

Revision ID: 9f6505d2db0c
Revises: 
Create Date: 2026-07-12 10:47:13.098065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f6505d2db0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_house_accounts_id'), table_name='house_accounts')
    op.drop_table('house_accounts')
    op.drop_index(op.f('ix_tip_distributions_id'), table_name='tip_distributions')
    op.drop_table('tip_distributions')
    op.drop_index(op.f('ix_service_requests_id'), table_name='service_requests')
    op.drop_table('service_requests')
    op.drop_index(op.f('ix_tip_pools_date'), table_name='tip_pools')
    op.drop_index(op.f('ix_tip_pools_id'), table_name='tip_pools')
    op.drop_table('tip_pools')
    op.drop_index(op.f('ix_order_templates_id'), table_name='order_templates')
    op.drop_table('order_templates')
    op.drop_index(op.f('ix_waitlist_entries_id'), table_name='waitlist_entries')
    op.drop_table('waitlist_entries')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_house_account_transactions_id'), table_name='house_account_transactions')
    op.drop_table('house_account_transactions')
    op.add_column('customers', sa.Column('tags', sa.String(), nullable=True))
    op.alter_column('customers', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('("")'))
    op.alter_column('customers', 'auth_token',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('("")'))
    op.alter_column('expenses', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('expenses', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('expenses', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('expenses', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'other'"))
    op.alter_column('expenses', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('expenses', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.add_column('ingredients', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.add_column('ingredients', sa.Column('barcode', sa.String(), nullable=True))
    op.create_foreign_key(None, 'ingredients', 'suppliers', ['supplier_id'], ['id'])
    op.add_column('menu_items', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('menu_items', sa.Column('tax_rate', sa.Float(), nullable=True))
    op.add_column('menu_items', sa.Column('allergens', sa.String(), nullable=True))
    op.add_column('menu_items', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('menu_items', sa.Column('translations', sa.String(), nullable=True))
    op.add_column('menu_items', sa.Column('calories', sa.Integer(), nullable=True))
    op.add_column('menu_items', sa.Column('protein', sa.Float(), nullable=True))
    op.add_column('menu_items', sa.Column('fat', sa.Float(), nullable=True))
    op.add_column('menu_items', sa.Column('carbs', sa.Float(), nullable=True))
    op.add_column('order_items', sa.Column('tax_rate', sa.Float(), nullable=True))
    op.add_column('order_items', sa.Column('tax_amount', sa.Float(), nullable=True))
    op.add_column('order_items', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('order_items', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('tax_total', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('tags', sa.String(), nullable=True))
    op.alter_column('orders', 'customer_phone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('("")'))
    op.alter_column('orders', 'customer_email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('("")'))
    op.alter_column('orders', 'delivery_address',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('("")'))
    op.add_column('purchase_order_items', sa.Column('received_quantity', sa.Float(), nullable=True))
    op.add_column('purchase_orders', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('purchase_orders', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.add_column('purchase_orders', sa.Column('received_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'purchase_orders', 'users', ['created_by'], ['id'])
    op.add_column('reservations', sa.Column('reminder_sent', sa.Integer(), nullable=True))
    op.add_column('stock_transactions', sa.Column('reference', sa.String(), nullable=True))
    op.alter_column('waste_records', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('waste_records', 'quantity',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('waste_records', 'cost',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('waste_records', 'reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'spoilage'"))
    op.alter_column('waste_records', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('waste_records', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index(op.f('ix_waste_records_id'), 'waste_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waste_records_id'), table_name='waste_records')
    op.alter_column('waste_records', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('waste_records', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('waste_records', 'reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'spoilage'"))
    op.alter_column('waste_records', 'cost',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('waste_records', 'quantity',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('waste_records', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('stock_transactions', 'reference')
    op.drop_column('reservations', 'reminder_sent')
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_column('purchase_orders', 'received_at')
    op.drop_column('purchase_orders', 'approved_at')
    op.drop_column('purchase_orders', 'created_by')
    op.drop_column('purchase_order_items', 'received_quantity')
    op.alter_column('orders', 'delivery_address',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('("")'))
    op.alter_column('orders', 'customer_email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('("")'))
    op.alter_column('orders', 'customer_phone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('("")'))
    op.drop_column('orders', 'tags')
    op.drop_column('orders', 'notes')
    op.drop_column('orders', 'scheduled_at')
    op.drop_column('orders', 'tax_total')
    op.drop_column('order_items', 'completed_at')
    op.drop_column('order_items', 'started_at')
    op.drop_column('order_items', 'tax_amount')
    op.drop_column('order_items', 'tax_rate')
    op.drop_column('menu_items', 'carbs')
    op.drop_column('menu_items', 'fat')
    op.drop_column('menu_items', 'protein')
    op.drop_column('menu_items', 'calories')
    op.drop_column('menu_items', 'translations')
    op.drop_column('menu_items', 'tags')
    op.drop_column('menu_items', 'allergens')
    op.drop_column('menu_items', 'tax_rate')
    op.drop_column('menu_items', 'image_url')
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.drop_column('ingredients', 'barcode')
    op.drop_column('ingredients', 'supplier_id')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.alter_column('expenses', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('expenses', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('expenses', 'category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'other'"))
    op.alter_column('expenses', 'amount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('expenses', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('expenses', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('customers', 'auth_token',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('("")'))
    op.alter_column('customers', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('("")'))
    op.drop_column('customers', 'tags')
    op.create_table('house_account_transactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('account_id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['house_accounts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_house_account_transactions_id'), 'house_account_transactions', ['id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_table('waitlist_entries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('party_size', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('branch_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('notified_at', sa.DATETIME(), nullable=True),
    sa.Column('seated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlist_entries_id'), 'waitlist_entries', ['id'], unique=False)
    op.create_table('order_templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('items_json', sa.TEXT(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_templates_id'), 'order_templates', ['id'], unique=False)
    op.create_table('tip_pools',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('branch_id', sa.INTEGER(), nullable=True),
    sa.Column('total_tips', sa.FLOAT(), nullable=True),
    sa.Column('method', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('distributed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tip_pools_id'), 'tip_pools', ['id'], unique=False)
    op.create_index(op.f('ix_tip_pools_date'), 'tip_pools', ['date'], unique=False)
    op.create_table('service_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('table_id', sa.INTEGER(), nullable=False),
    sa.Column('table_name', sa.VARCHAR(), nullable=True),
    sa.Column('request_type', sa.VARCHAR(), nullable=False),
    sa.Column('message', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('acknowledged_at', sa.DATETIME(), nullable=True),
    sa.Column('acknowledged_by', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_requests_id'), 'service_requests', ['id'], unique=False)
    op.create_table('tip_distributions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pool_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('hours_worked', sa.FLOAT(), nullable=True),
    sa.Column('role_weight', sa.FLOAT(), nullable=True),
    sa.Column('paid', sa.BOOLEAN(), nullable=True),
    sa.Column('paid_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['pool_id'], ['tip_pools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tip_distributions_id'), 'tip_distributions', ['id'], unique=False)
    op.create_table('house_accounts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('balance', sa.FLOAT(), nullable=True),
    sa.Column('credit_limit', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_index(op.f('ix_house_accounts_id'), 'house_accounts', ['id'], unique=False)
    # ### end Alembic commands ###
